# Generated by Django 6.0.5 on 2026-05-19 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('CPF_Paciente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('CPF_Responsavel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Responsavel',
            },
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id_sintoma', models.AutoField(primary_key=True, serialize=False)),
                ('sintoma', models.CharField(max_length=50)),
                ('peso_masc', models.IntegerField()),
                ('peso_fem', models.IntegerField()),
            ],
            options={
                'db_table': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='Sintomas_do_paciente',
            fields=[
                ('id_sintomas', models.AutoField(primary_key=True, serialize=False)),
                ('sintomas', models.TextField()),
            ],
            options={
                'db_table': 'Sintomas_do_paciente',
            },
        ),
        migrations.CreateModel(
            name='historico_de_consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_de_consulta', models.DateField()),
                ('medico', models.ForeignKey(db_column='id_medico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='api.medico')),
                ('paciente', models.ForeignKey(db_column='CPF_Paciente', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.paciente')),
                ('responsavel', models.ForeignKey(db_column='CPF_Responsavel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='api.responsavel')),
                ('sintomas', models.ForeignKey(db_column='id_sintomas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.sintomas_do_paciente')),
            ],
            options={
                'db_table': 'historico_de_consulta',
            },
        ),
    ]
